import { type NextPage } from "next";
import { SignInButton, useUser, useClerk } from "@clerk/nextjs";
import Head from "next/head";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  const { signOut } = useClerk();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user.isSignedIn && <SignInButton mode="modal" />}
      {user.isSignedIn && <button onClick={() => signOut()}>Sign Out</button>}
    </>
  );
};

export default Home;
